version: 2.1

orbs:
  node: circleci/node@6

jobs:

  install:
    docker:
      - image: cimg/node:22.22.2
    steps:
      - checkout
      - run:
          name: "Versiones"
          command: |
            node -v
            npm -v
      - node/install-packages:
          pkg-manager: npm
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    docker:
      - image: cimg/node:22.22.2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Lint (Prettier)"
          command: npm run lint
      - run:
          name: "Branch info"
          when: always
          command: |
            echo "Branch: $CIRCLE_BRANCH"

  test:
    docker:
      - image: cimg/node:22.22.2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Tests"
          command: npm test
      - run:
          name: "Branch info"
          when: always
          command: |
            echo "Branch: $CIRCLE_BRANCH"

  audit:
    docker:
      - image: cimg/node:22.22.2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Audit"
          command: npm audit --audit-level moderate
      - run:
          name: "Branch info"
          when: always
          command: |
            echo "Branch: $CIRCLE_BRANCH"

  build:
    docker:
      - image: cimg/node:22.22.2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Build Angular"
          command: npm run build -- --configuration production
      - run:
          name: "Branch info"
          when: always
          command: |
            echo "Branch: $CIRCLE_BRANCH | Build+Archive: true"
      - store_artifacts:
          path: dist
          destination: build

workflows:
  ci:
    jobs:
      - install

      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - audit:
          requires:
            - install

      - build:
          requires:
            - lint
            - test
            - audit
          filters:
            branches:
              only:
                - main
                - master
                - ci/cd
                - /^release\/.*/
